{{$globalValues := .Values.global }}
{{- range .Values.global.namespaces }}  

apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount
  namespace: {{ . | lower | quote }}
---
{{- end -}}